<?php

namespace AppBundle\Repository;

/**
 * TranslatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranslatorRepository extends \Doctrine\ORM\EntityRepository
{
}
