<?php

namespace AppBundle\Repository;

/**
 * WorkStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
